<?php

namespace TaskPlannerBundle\Entity;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    // This method is essential for filtering categories by user that created them.
    public function findByUser(User $user)
    {
        return $this->findBy(array("user" => $user));
    }
}
